interface Resources {
  "account": {
    "detail_infomation": "Detail infomation",
    "account_manager": "My account",
    "my_reservations": "My reservations",
    "log_out": "Log out",
    "YOU’RE": "YOU’RE",
    "New_Citizen": "New Citizen",
    "Night": "Night(s)",
    "Booking": "Booking(s)",
    "Full_name": "Full name",
    "Nationality": "Nationality",
    "Phone_number": "Phone number",
    "Password": "Password",
    "Change_password": "Change password",
    "Current_password": "Current password",
    "New_password": "New password",
    "Confirm new password": "Confirm new password",
    "Cancel": "Cancel",
    " Must have at least 8 characters": " Must have at least 8 characters",
    "Contain uppercase and lowercase": "Contain uppercase and lowercase",
    "Contain a number": "Contain a number",
    "Contain a symbol": "Contain a symbol",
    "Personal_details": "Personal details",
    "Peronsal_info": "Peronsal info",
    "Save_changes": " Save changes",
    "placeholder": {
      "email": "Enter your email",
      "current_password": "Enter your password",
      "confirm_password": "Confirm your password",
      "full_name": "Enter your full name",
      "phone_number": "Enter your phone number",
      "new_password": "Enter new password",
      "confirm_new_password": "Confirm your new password"
    },
    "gender": "Gender",
    "male": "Male",
    "female": "Female",
    "date_of_birth": "Date of birth",
    "upcoming": "Upcoming",
    "completed": "Completed",
    "cancelled": "Cancelled"
  },
  "booking": {
    "customer_information": "Customer information",
    "payment_information": "Payment information",
    "confirm_booking": "Confirm booking",
    "required": {
      "email": "Email is required",
      "phone": "Phone is required"
    },
    "validate": {
      "email": "Email is invalid",
      "phone": "Phone is invalid",
      "special_requests": "Special requests must be at least 10 characters long"
    },
    "button": "Book now",
    "title": "Complete your booking",
    "subtitle": "Check everything is okay? Great! Secure your stay.",
    "booking": {
      "button": "Đặt phòng",
      "title": "Hoàn tất đặt phòng của bạn",
      "subtitle": "Kiểm tra kỹ mọi thứ đã ổn chưa? Tuyệt vời! Tiến hành bảo đảm chỗ ở của bạn.",
      "citizen_text": "Xin chào {{name}}!",
      "citizen_text2": " Hãy tận hưởng những đặc quyền này bằng cách hoàn tất đặt phòng này:",
      "citizen_subtext": "Đăng nhập với tư cách Hoàng Kim Chi",
      "citizen_level_label": "Hội viên MỚI",
      "contact": "Thông tin liên hệ",
      "contact_alert": "Vui lòng điền đầy đủ các trường thông tin để đảm bảo bạn nhận được xác nhận đặt phòng qua email.",
      "input_label": "Tên đầy đủ của bạn ",
      "nameinput_placeholder": "Nhập họ và tên",
      "input_note": "Để cập nhật Thông tin liên hệ, vui lòng truy cập trang ",
      "input_note_link": "Tài khoản",
      "email_label": "Email của bạn",
      "email_placeholder": "Nhập email",
      "email_note": "Thông tin đặt phòng sẽ được gửi tới email này",
      "phone_label": "Số điện thoại di động của bạn",
      "phone_placeholder": "Nhập số điện thoại",
      "guest_switch_option1": "Tôi là khách hàng",
      "guest_switch_option2": "Tôi đặt phòng cho người khác",
      "textarea": "Yêu cầu đặc biệt hoặc sở thích",
      "srtitle": "Yêu cầu đặc biệt hoặc sở thích",
      "srsubtitle": "Bạn sẽ biết tình trạng có sẵn của yêu cầu bổ sung trong quá trình nhận phòng. Có thể phát sinh phí bổ sung nhưng bạn vẫn có thể hủy yêu cầu sau đó.",
      "submit": "Tiếp tục thanh toán"
    },
    "payment": {
      "method_title": "Bạn muốn thanh toán bằng phương thức nào?",
      "img": "Thanh toán bằng mã QR",
      "method_option1": "Thanh toán bằng mã QR",
      "method_option2": "Ví điện tử & Ứng dụng ngân hàng",
      "method_option3": "Thẻ tín dụng/ghi nợ",
      "method_option4": "Thẻ ATM/Tài khoản ngân hàng",
      "note_1": "Hãy đảm bảo rằng bạn có bất kỳ ví điện tử hoặc ứng dụng ngân hàng di động nào hỗ trợ thanh toán bằng mã QR.",
      "note_2": "Một mã QR sẽ xuất hiện sau khi bạn nhấp vào nút 'Thanh toán'. Chỉ cần lưu hoặc chụp màn hình mã QR để hoàn tất thanh toán trong thời hạn quy định.",
      "note_3": "Vui lòng sử dụng mã QR mới nhất được cung cấp để hoàn tất thanh toán.",
      "promotion_title": "Áp dụng mã khuyến mãi?",
      "input_text": "Nhập mã khuyến mãi ở đây",
      "promotion_apply_button": "Áp dụng",
      "detail_title": "Chi tiết thanh toán",
      "room_info": "(x1) Phòng Deluxe Twin Park View - 2 Khách",
      "room_price": "2.200.000 VND",
      "total_price_title": "Tổng tiền",
      "total_price": "2.200.000 VND",
      "submit": "Tiếp tục với ",
      "note_text": "Bằng cách tiếp tục thanh toán, bạn đã đồng ý với M Village và các Điều khoản & Chính sách Bảo mật"
    }
  },
  "common": {
    "hello": "Welcome",
    "world": "World",
    "lng_vi": "Tiếng Việt",
    "lng_en": "English",
    "booking": "Booking",
    "route": {
      "home": "Home",
      "about": "About",
      "contact": "Contact",
      "search_room": "Search Room",
      "recruitment": "Recruitment",
      "login": "Login/Register",
      "follow": "Folow us  via"
    },
    "policies": {
      "policy": "Policy",
      "privacy": "Privacy Policy",
      "terms": "Terms of Service",
      "faqs": "FAQs"
    },
    "feedback": {
      "title": "Your experience at A HOMVILLA is very important to us",
      "para": "Share your thoughts on how we can craft an even better experience for you next time",
      "share": "Share your thoughts"
    },
    "content": {
      "header": "The Living Stories Collective",
      "title": "Discover the Latest at A HOMEVILLA"
    },
    "village": {
      "newDN": "NEW VILLAGE: DA NANG",
      "nameDN": "A HOMEVILLA Hotel Da Nang Centre",
      "desDN": "Just launched, A HOMEVILLA offers a perfect Da Nang experience with a central location and sunlit rooms. Enjoy a voucher worth 1.5 million VND for the most local destinations.",
      "booking": "Book now",
      "newHCM": "NEW VILLAGE: HO CHI MINH",
      "desHCM1": "An ideal base to dive in Saigon-Chợ Lớn’s culture! Located at the intersection of District 1 & 5, featuring Chinese design, with flexible services and amenities.",
      "desHCM2": "Choose Express Nguyen Binh Khiem for a convenient yet peaceful business trip in District 1. All options has separate bedrooms, living rooms and private kitchens."
    },
    "auth": {
      "welcome": "A world of booking privileges and benefits awaits you!",
      "login": "Login",
      "register": "Register",
      "logout": "Logout",
      "email": "Email",
      "password": "Password",
      "confirm_password": "Confirm Password",
      "forgot_password": "Forgot Password",
      "remember_me": "Remember Me",
      "phone": "Phone number",
      "email_or_phone": "Email or Phone",
      "name": "Name",
      "dont_have_account": "Don't have account yet?",
      "have_account": "Already have an account?",
      "placeholder": {
        "email_or_phone": "Enter your email or phone",
        "password": "Enter your password",
        "confirm_password": "Enter your confirm password",
        "phone": "Enter your phone number",
        "email": "Enter your email",
        "name": "Enter your name",
        "current_password": "Enter your current password",
        "new_password": "Enter your new password",
        "confirm_new_password": "Enter your confirm new password"
      },
      "register_success": "Register successfully. Please check your email to activate your account",
      "register_error": "Register failed. Please try again",
      "active_account_success": "Activate account successfully",
      "active_account_error": "Activate account failed",
      "enter_otp": "Enter the OTP sent to your {{field}}",
      "login_success": "Login successfully",
      "login_error": "Login failed",
      "required": {
        "email_or_phone": "Email/Phone is required",
        "name": "Name is required",
        "otp": "OTP is required",
        "password": "Password is required",
        "confirm_password": "Confirm password is required"
      },
      "validate": {
        "email_or_phone": "Invalid email or phone",
        "password_min_length": "Password must be at least 8 characters",
        "password_uppercase": "Password must have at least 1 uppercase letter",
        "password_lowercase": "Password must have at least 1 lowercase letter",
        "password_digit": "Password must have at least 1 digit",
        "password_special": "Password must have at least 1 special character",
        "password_match": "Password does not match"
      }
    },
    "bookingform": {
      "location": "Where",
      "placeholder_location": "Your leisure trip?",
      "checkIn": "Check in",
      "checkOut": "Check out",
      "occupancy": "Guest",
      "guests": "Guests",
      "search": "Find room",
      "explore": "Explore",
      "adults": "Adults",
      "children": "Children",
      "baby": "Baby",
      "adults_description": "Older than 18 years old",
      "children_description": "From 6 to 18 years old",
      "baby_description": "Less than 6 years old",
      "apply": "Apply"
    },
    "select_date": {
      "hourly": "Hourly",
      "daily": "Daily",
      "nightly": "Over night",
      "check_in_time": "Check-in time",
      "check_in_placeholder": "Select check-in time",
      "duration": "Duration",
      "duration_placeholder": "Select duration",
      "duration_hours_one": "{{count}} hour",
      "duration_hours_other": "{{count}} hours"
    },
    "hanoi": "Hanoi",
    "ho_chi_minh": "Ho Chi Minh"
  },
  "home": {
    "explore": "Explore"
  },
  "searchroom": {
    "searchroom": {
      "pricetitle": "Price range",
      "priceSubtitle": "1 room, 1 night",
      "viewmap": "View map",
      "button": "Reset"
    },
    "booking": {
      "button": "Book now",
      "title": "Complete Your Booking",
      "subtitle": "Double-check everything looks good? Great! Proceed to secure your stay.",
      "citizen_text": "Xin chào {{name}}!",
      "citizen_text2": " Hãy tận hưởng những đặc quyền này bằng cách hoàn tất đặt phòng này:",
      "citizen_subtext": "Đăng nhập với tư cách Hoàng Kim Chi",
      "citizen_level_label": "Hội viên MỚI",
      "contact": "Thông tin liên hệ",
      "contact_alert": "Vui lòng điền đầy đủ các trường thông tin để đảm bảo bạn nhận được xác nhận đặt phòng qua email.",
      "input_label": "Tên đầy đủ của bạn ",
      "nameinput_placeholder": "Nhập họ và tên",
      "input_note": "Để cập nhật Thông tin liên hệ, vui lòng truy cập trang ",
      "input_note_link": "Tài khoản",
      "email_label": "Email của bạn",
      "email_placeholder": "Nhập email",
      "email_note": "Thông tin đặt phòng sẽ được gửi tới email này",
      "phone_label": "Số điện thoại di động của bạn",
      "phone_placeholder": "Nhập số điện thoại",
      "guest_switch_option1": "Tôi là khách hàng",
      "guest_switch_option2": "Tôi đặt phòng cho người khác",
      "textarea": "Yêu cầu đặc biệt hoặc sở thích",
      "srtitle": "Yêu cầu đặc biệt hoặc sở thích",
      "srsubtitle": "Bạn sẽ biết tình trạng có sẵn của yêu cầu bổ sung trong quá trình nhận phòng. Có thể phát sinh phí bổ sung nhưng bạn vẫn có thể hủy yêu cầu sau đó.",
      "submit": "Tiếp tục thanh toán"
    },
    "payment": {
      "method_title": "Bạn muốn thanh toán bằng phương thức nào?",
      "img": "Thanh toán bằng mã QR",
      "method_option1": "Thanh toán bằng mã QR",
      "method_option2": "Ví điện tử & Ứng dụng ngân hàng",
      "method_option3": "Thẻ tín dụng/ghi nợ",
      "method_option4": "Thẻ ATM/Tài khoản ngân hàng",
      "note_1": "Hãy đảm bảo rằng bạn có bất kỳ ví điện tử hoặc ứng dụng ngân hàng di động nào hỗ trợ thanh toán bằng mã QR.",
      "note_2": "Một mã QR sẽ xuất hiện sau khi bạn nhấp vào nút 'Thanh toán'. Chỉ cần lưu hoặc chụp màn hình mã QR để hoàn tất thanh toán trong thời hạn quy định.",
      "note_3": "Vui lòng sử dụng mã QR mới nhất được cung cấp để hoàn tất thanh toán.",
      "promotion_title": "Áp dụng mã khuyến mãi?",
      "input_text": "Nhập mã khuyến mãi ở đây",
      "promotion_apply_button": "Áp dụng",
      "detail_title": "Chi tiết thanh toán",
      "room_info": "(x1) Phòng Deluxe Twin Park View - 2 Khách",
      "room_price": "2.200.000 VND",
      "total_price_title": "Tổng tiền",
      "total_price": "2.200.000 VND",
      "submit": "Tiếp tục với ",
      "note_text": "Bằng cách tiếp tục thanh toán, bạn đã đồng ý với M Village và các Điều khoản & Chính sách Bảo mật"
    }
  }
}

export default Resources;
