export const STORE_TOKEN_KEY = {
  AHOMEVILLA_CLIENT_TOKEN: 'AHOMEVILLA_CLIENT_TOKEN',
  AHOMEVILLA_CLIENT_REFRESH_TOKEN: 'AHOMEVILLA_CLIENT_REFRESH_TOKEN',
  AHOMEVILLA_CLIENT_EXPIRE_TIME: 'AHOMEVILLA_CLIENT_EXPIRE_TIME',
};
